#!/usr/bin/env bash
# merge.sh — Assembles all written chapters into book_complete.md
# Run from the project root: bash merge.sh
# Output: book_complete.md (separate from book.md which holds references)

set -euo pipefail

OUTPUT="book_complete.md"
PARTS_DIR="parts"
TEMP=$(mktemp)

echo "Merging chapters into $OUTPUT..."

{
  echo "# SDE Mastery Book — Complete Edition"
  echo ""
  echo "> *Generated by merge.sh on $(date '+%Y-%m-%d %H:%M')*"
  echo "> *Edit individual chapter files in \`parts/\`, then re-run merge.sh*"
  echo ""
  echo "---"
  echo ""
} > "$TEMP"

# Helper: append a file if it exists, with a trailing blank line
append_if_exists() {
  local file="$1"
  if [[ -f "$file" ]]; then
    cat "$file" >> "$TEMP"
    echo "" >> "$TEMP"
    echo "---" >> "$TEMP"
    echo "" >> "$TEMP"
    echo "  + $file"
  fi
}

# ─── Part 1 (Ch 1–8) ───────────────────────────────────────────────────────
echo ""
echo "Part 1..."
append_if_exists "$PARTS_DIR/part_1/part_1.md"
for ch in 1 2 3 4 5 6 7 8; do
  append_if_exists "$PARTS_DIR/part_1/ch_${ch}.md"
done

# ─── Part 2 (Ch 9–17) ──────────────────────────────────────────────────────
echo ""
echo "Part 2..."
append_if_exists "$PARTS_DIR/part_2/part_2.md"
for ch in 9 10 11 12 13 14 15 16 17; do
  append_if_exists "$PARTS_DIR/part_2/ch_${ch}.md"
done

# ─── Part 3 (Ch 18–27) ─────────────────────────────────────────────────────
echo ""
echo "Part 3..."
append_if_exists "$PARTS_DIR/part_3/part_3.md"
for ch in 18 19 20 21 22 23 24 25 26 27; do
  append_if_exists "$PARTS_DIR/part_3/ch_${ch}.md"
done

# ─── Part 4 (Ch 28–55) ─────────────────────────────────────────────────────
echo ""
echo "Part 4..."
append_if_exists "$PARTS_DIR/part_4/part_4.md"
for ch in $(seq 28 55); do
  append_if_exists "$PARTS_DIR/part_4/ch_${ch}.md"
done

# ─── Part 5 (Ch 56–70) ─────────────────────────────────────────────────────
echo ""
echo "Part 5..."
append_if_exists "$PARTS_DIR/part_5/part_5.md"
for ch in $(seq 56 70); do
  append_if_exists "$PARTS_DIR/part_5/ch_${ch}.md"
done

# ─── Part 6 (P01–P24) ──────────────────────────────────────────────────────
echo ""
echo "Part 6..."
append_if_exists "$PARTS_DIR/part_6/part_6.md"
for n in $(seq -w 1 24); do
  append_if_exists "$PARTS_DIR/part_6/p${n}.md"
done

# ─── Part 7 (Ch 71–76) ─────────────────────────────────────────────────────
echo ""
echo "Part 7..."
append_if_exists "$PARTS_DIR/part_7/part_7.md"
for ch in 71 72 73 74 75 76; do
  append_if_exists "$PARTS_DIR/part_7/ch_${ch}.md"
done

# ─── Move temp to output ────────────────────────────────────────────────────
mv "$TEMP" "$OUTPUT"

# Count words and chapters
WORDS=$(wc -w < "$OUTPUT" | tr -d ' ')
CHAPTERS=$(grep -c '^## Chapter ' "$OUTPUT" 2>/dev/null || echo 0)
PROJECTS=$(grep -c '^## P[0-9]' "$OUTPUT" 2>/dev/null || echo 0)

echo ""
echo "✓ Done: $OUTPUT"
echo "  Words:    $WORDS"
echo "  Chapters: $CHAPTERS"
echo "  Projects: $PROJECTS"
echo ""
echo "  book.md         → reference version (links to parts/)"
echo "  book_complete.md → this file (all content inline)"
